[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://cloud-clip-api-107631450464.us-central1.run.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
